name: Kubernetes Validation

on:
  workflow_dispatch:

jobs:
  k8s-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Substituir variável
        run: |
          sed -i 's|\${IMAGE_REPO}|${{ secrets.DOCKER_REPO }}|g' Projeto/K8s/deployment.yaml

      - name: Instalar kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: Validar manifestos
        run: kubeconform -strict -summary Projeto/K8s/*.yaml